package cc.ikevin.community.model;

public class Thumb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb.id
     *
     * @mbg.generated Sat Aug 10 15:33:19 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb.target_id
     *
     * @mbg.generated Sat Aug 10 15:33:19 CST 2019
     */
    private Long targetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb.type
     *
     * @mbg.generated Sat Aug 10 15:33:19 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb.liker
     *
     * @mbg.generated Sat Aug 10 15:33:19 CST 2019
     */
    private Long liker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb.gmt_create
     *
     * @mbg.generated Sat Aug 10 15:33:19 CST 2019
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb.gmt_modified
     *
     * @mbg.generated Sat Aug 10 15:33:19 CST 2019
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb.id
     *
     * @return the value of thumb.id
     *
     * @mbg.generated Sat Aug 10 15:33:19 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb.id
     *
     * @param id the value for thumb.id
     *
     * @mbg.generated Sat Aug 10 15:33:19 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb.target_id
     *
     * @return the value of thumb.target_id
     *
     * @mbg.generated Sat Aug 10 15:33:19 CST 2019
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb.target_id
     *
     * @param targetId the value for thumb.target_id
     *
     * @mbg.generated Sat Aug 10 15:33:19 CST 2019
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb.type
     *
     * @return the value of thumb.type
     *
     * @mbg.generated Sat Aug 10 15:33:19 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb.type
     *
     * @param type the value for thumb.type
     *
     * @mbg.generated Sat Aug 10 15:33:19 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb.liker
     *
     * @return the value of thumb.liker
     *
     * @mbg.generated Sat Aug 10 15:33:19 CST 2019
     */
    public Long getLiker() {
        return liker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb.liker
     *
     * @param liker the value for thumb.liker
     *
     * @mbg.generated Sat Aug 10 15:33:19 CST 2019
     */
    public void setLiker(Long liker) {
        this.liker = liker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb.gmt_create
     *
     * @return the value of thumb.gmt_create
     *
     * @mbg.generated Sat Aug 10 15:33:19 CST 2019
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb.gmt_create
     *
     * @param gmtCreate the value for thumb.gmt_create
     *
     * @mbg.generated Sat Aug 10 15:33:19 CST 2019
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb.gmt_modified
     *
     * @return the value of thumb.gmt_modified
     *
     * @mbg.generated Sat Aug 10 15:33:19 CST 2019
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb.gmt_modified
     *
     * @param gmtModified the value for thumb.gmt_modified
     *
     * @mbg.generated Sat Aug 10 15:33:19 CST 2019
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}