package cn.niter.forum.model;

public class News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_id
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    private Long newsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.description
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.html
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    private String html;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.source
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.link
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.pub_date
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    private String pubDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.imageurl1
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    private String imageurl1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.imageurl2
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    private String imageurl2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.imageurl3
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    private String imageurl3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.tag
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.view_count
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.comment_count
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.like_count
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.gmt_latest_comment
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    private Long gmtLatestComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.status
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.column2
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    private Integer column2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.gmt_create
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.gmt_modified
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_id
     *
     * @return the value of news.news_id
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public Long getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_id
     *
     * @param newsId the value for news.news_id
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public void setNewsId(Long newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.description
     *
     * @return the value of news.description
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.description
     *
     * @param description the value for news.description
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.html
     *
     * @return the value of news.html
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public String getHtml() {
        return html;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.html
     *
     * @param html the value for news.html
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public void setHtml(String html) {
        this.html = html == null ? null : html.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.source
     *
     * @return the value of news.source
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.source
     *
     * @param source the value for news.source
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.link
     *
     * @return the value of news.link
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.link
     *
     * @param link the value for news.link
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.pub_date
     *
     * @return the value of news.pub_date
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public String getPubDate() {
        return pubDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.pub_date
     *
     * @param pubDate the value for news.pub_date
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public void setPubDate(String pubDate) {
        this.pubDate = pubDate == null ? null : pubDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.imageurl1
     *
     * @return the value of news.imageurl1
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public String getImageurl1() {
        return imageurl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.imageurl1
     *
     * @param imageurl1 the value for news.imageurl1
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public void setImageurl1(String imageurl1) {
        this.imageurl1 = imageurl1 == null ? null : imageurl1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.imageurl2
     *
     * @return the value of news.imageurl2
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public String getImageurl2() {
        return imageurl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.imageurl2
     *
     * @param imageurl2 the value for news.imageurl2
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public void setImageurl2(String imageurl2) {
        this.imageurl2 = imageurl2 == null ? null : imageurl2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.imageurl3
     *
     * @return the value of news.imageurl3
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public String getImageurl3() {
        return imageurl3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.imageurl3
     *
     * @param imageurl3 the value for news.imageurl3
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public void setImageurl3(String imageurl3) {
        this.imageurl3 = imageurl3 == null ? null : imageurl3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.tag
     *
     * @return the value of news.tag
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.tag
     *
     * @param tag the value for news.tag
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.view_count
     *
     * @return the value of news.view_count
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.view_count
     *
     * @param viewCount the value for news.view_count
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.comment_count
     *
     * @return the value of news.comment_count
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.comment_count
     *
     * @param commentCount the value for news.comment_count
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.like_count
     *
     * @return the value of news.like_count
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.like_count
     *
     * @param likeCount the value for news.like_count
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.gmt_latest_comment
     *
     * @return the value of news.gmt_latest_comment
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public Long getGmtLatestComment() {
        return gmtLatestComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.gmt_latest_comment
     *
     * @param gmtLatestComment the value for news.gmt_latest_comment
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public void setGmtLatestComment(Long gmtLatestComment) {
        this.gmtLatestComment = gmtLatestComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.status
     *
     * @return the value of news.status
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.status
     *
     * @param status the value for news.status
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.column2
     *
     * @return the value of news.column2
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public Integer getColumn2() {
        return column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.column2
     *
     * @param column2 the value for news.column2
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public void setColumn2(Integer column2) {
        this.column2 = column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.gmt_create
     *
     * @return the value of news.gmt_create
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.gmt_create
     *
     * @param gmtCreate the value for news.gmt_create
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.gmt_modified
     *
     * @return the value of news.gmt_modified
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.gmt_modified
     *
     * @param gmtModified the value for news.gmt_modified
     *
     * @mbg.generated Mon Feb 17 23:10:20 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}