package cn.niter.forum.model;

public class Talk {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.id
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.title
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.description
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.tag
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.images
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    private String images;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.video
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    private String video;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.type
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.status
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.permission
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    private Integer permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.creator
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.view_count
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.comment_count
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.like_count
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.gmt_latest_comment
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    private Long gmtLatestComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.gmt_create
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.gmt_modified
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.id
     *
     * @return the value of talk.id
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.id
     *
     * @param id the value for talk.id
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.title
     *
     * @return the value of talk.title
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.title
     *
     * @param title the value for talk.title
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.description
     *
     * @return the value of talk.description
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.description
     *
     * @param description the value for talk.description
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.tag
     *
     * @return the value of talk.tag
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.tag
     *
     * @param tag the value for talk.tag
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.images
     *
     * @return the value of talk.images
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.images
     *
     * @param images the value for talk.images
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.video
     *
     * @return the value of talk.video
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.video
     *
     * @param video the value for talk.video
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public void setVideo(String video) {
        this.video = video == null ? null : video.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.type
     *
     * @return the value of talk.type
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.type
     *
     * @param type the value for talk.type
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.status
     *
     * @return the value of talk.status
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.status
     *
     * @param status the value for talk.status
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.permission
     *
     * @return the value of talk.permission
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public Integer getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.permission
     *
     * @param permission the value for talk.permission
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public void setPermission(Integer permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.creator
     *
     * @return the value of talk.creator
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.creator
     *
     * @param creator the value for talk.creator
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.view_count
     *
     * @return the value of talk.view_count
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.view_count
     *
     * @param viewCount the value for talk.view_count
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.comment_count
     *
     * @return the value of talk.comment_count
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.comment_count
     *
     * @param commentCount the value for talk.comment_count
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.like_count
     *
     * @return the value of talk.like_count
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.like_count
     *
     * @param likeCount the value for talk.like_count
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.gmt_latest_comment
     *
     * @return the value of talk.gmt_latest_comment
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public Long getGmtLatestComment() {
        return gmtLatestComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.gmt_latest_comment
     *
     * @param gmtLatestComment the value for talk.gmt_latest_comment
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public void setGmtLatestComment(Long gmtLatestComment) {
        this.gmtLatestComment = gmtLatestComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.gmt_create
     *
     * @return the value of talk.gmt_create
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.gmt_create
     *
     * @param gmtCreate the value for talk.gmt_create
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.gmt_modified
     *
     * @return the value of talk.gmt_modified
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.gmt_modified
     *
     * @param gmtModified the value for talk.gmt_modified
     *
     * @mbg.generated Wed Sep 23 18:14:48 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}