package cn.niter.forum.model;

public class UserAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.id
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.user_id
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.group_id
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.vip_rank
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    private Integer vipRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.score
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.score1
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    private Integer score1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.score2
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    private Integer score2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.score3
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    private Integer score3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.id
     *
     * @return the value of user_account.id
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.id
     *
     * @param id the value for user_account.id
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.user_id
     *
     * @return the value of user_account.user_id
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.user_id
     *
     * @param userId the value for user_account.user_id
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.group_id
     *
     * @return the value of user_account.group_id
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.group_id
     *
     * @param groupId the value for user_account.group_id
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.vip_rank
     *
     * @return the value of user_account.vip_rank
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public Integer getVipRank() {
        return vipRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.vip_rank
     *
     * @param vipRank the value for user_account.vip_rank
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public void setVipRank(Integer vipRank) {
        this.vipRank = vipRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.score
     *
     * @return the value of user_account.score
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.score
     *
     * @param score the value for user_account.score
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.score1
     *
     * @return the value of user_account.score1
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public Integer getScore1() {
        return score1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.score1
     *
     * @param score1 the value for user_account.score1
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public void setScore1(Integer score1) {
        this.score1 = score1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.score2
     *
     * @return the value of user_account.score2
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public Integer getScore2() {
        return score2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.score2
     *
     * @param score2 the value for user_account.score2
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public void setScore2(Integer score2) {
        this.score2 = score2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.score3
     *
     * @return the value of user_account.score3
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public Integer getScore3() {
        return score3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.score3
     *
     * @param score3 the value for user_account.score3
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public void setScore3(Integer score3) {
        this.score3 = score3;
    }
}