package cn.niter.forum.model;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.realname
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.userdetail
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    private String userdetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.birthday
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.marriage
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    private String marriage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.sex
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.blood
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    private String blood;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.figure
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    private String figure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.constellation
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    private String constellation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.education
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.trade
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    private String trade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.job
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.location
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    private String location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.realname
     *
     * @return the value of user_info.realname
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.realname
     *
     * @param realname the value for user_info.realname
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.userdetail
     *
     * @return the value of user_info.userdetail
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public String getUserdetail() {
        return userdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.userdetail
     *
     * @param userdetail the value for user_info.userdetail
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public void setUserdetail(String userdetail) {
        this.userdetail = userdetail == null ? null : userdetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.birthday
     *
     * @return the value of user_info.birthday
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.birthday
     *
     * @param birthday the value for user_info.birthday
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.marriage
     *
     * @return the value of user_info.marriage
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public String getMarriage() {
        return marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.marriage
     *
     * @param marriage the value for user_info.marriage
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public void setMarriage(String marriage) {
        this.marriage = marriage == null ? null : marriage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.sex
     *
     * @return the value of user_info.sex
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.sex
     *
     * @param sex the value for user_info.sex
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.blood
     *
     * @return the value of user_info.blood
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public String getBlood() {
        return blood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.blood
     *
     * @param blood the value for user_info.blood
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public void setBlood(String blood) {
        this.blood = blood == null ? null : blood.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.figure
     *
     * @return the value of user_info.figure
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public String getFigure() {
        return figure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.figure
     *
     * @param figure the value for user_info.figure
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public void setFigure(String figure) {
        this.figure = figure == null ? null : figure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.constellation
     *
     * @return the value of user_info.constellation
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public String getConstellation() {
        return constellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.constellation
     *
     * @param constellation the value for user_info.constellation
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public void setConstellation(String constellation) {
        this.constellation = constellation == null ? null : constellation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.education
     *
     * @return the value of user_info.education
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.education
     *
     * @param education the value for user_info.education
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.trade
     *
     * @return the value of user_info.trade
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public String getTrade() {
        return trade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.trade
     *
     * @param trade the value for user_info.trade
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public void setTrade(String trade) {
        this.trade = trade == null ? null : trade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.job
     *
     * @return the value of user_info.job
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.job
     *
     * @param job the value for user_info.job
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.location
     *
     * @return the value of user_info.location
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.location
     *
     * @param location the value for user_info.location
     *
     * @mbg.generated Fri Jan 31 23:10:34 CST 2020
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }
}